# Generated by Django 4.0.1 on 2022-01-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_answer_author_answer_modify_date_answer_voter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='data_format',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
