# Generated by Django 4.0.1 on 2022-01-12 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_question_data_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='data_format',
            new_name='url',
        ),
    ]
